### ISSUE TITLE
Any way to get the images back into the Build Guide?

### ISSUE THREAD

**Issue by starmandeluxe** [ffont/ddrm-tools#1]
I guess the old domain changed so the links broke. I heard the images were floating around somewhere. Any way to add them locally to this repo?

**Comment by ffont** [comment]
Hi, because the original pictures are now gone, I decided to upload my local copies of them. I hope Black Corp does not get angry about that. So now the interactive build guide is up and running again. As a bonus track, for motherboard pictures, starting on step ~28, I highlighted in yellow the changes compared to the previous step. This was helpful for me :)

**Comment by starmandeluxe** [comment]
Wow, thank you so much! Indeed I can see it now. You're awesome!
